### ISSUE TITLE
Redux and React-Redux not included?

### ISSUE THREAD

**Issue by gabrielkunkel** [stylesuxx/generator-react-webpack-redux#26] opened 2016-05-07 20:55 UTC
I tried doing a search for this issue but couldn't find anything, maybe I missed it, but I had to npm install react and react-redux for this to start working. Are you leaving it out for any particular reason?

**Comment by stylesuxx** [comment] 2016-05-11 14:18
Interesting, it should be installed as last step of the generator => https://github.com/stylesuxx/generator-react-webpack-redux/blob/master/generators/app/index.js#L38

Did you had any errors during running the generator?
Can you please tell me your nodeJS and npm version so I can try to reproduce

**Comment by stylesuxx** [comment] 2016-06-20 12:30
Closing this down since I can not reproduce it. Feel free to re open and provide with more information.

**Closed by stylesuxx** 2016-06-20 12:30 UTC
Labels: info needed
