### ISSUE TITLE
Cannot run npm start

### ISSUE THREAD

**Issue by phellipeandrade** [stylesuxx/generator-react-webpack-redux#51] opened 2016-11-06 14:33 UTC
##### Specific Details
I can not boot project through '**npm start**'

**System**: Ubuntu 16.04.1
**Node**: v6.9.1
**Npm**: 3.10.9

##### NPM DEBUG LOG

0 info it worked if it ends with ok
1 verbose cli [ '/home/phellipe/.nvm/versions/node/v6.9.1/bin/node',
1 verbose cli   '/home/phellipe/.nvm/versions/node/v6.9.1/bin/npm',
1 verbose cli   'bugs',
1 verbose cli   'react-webpack-redux' ]
2 info using npm@3.10.9
3 info using node@v6.9.1
4 silly fetchPackageMetaData react-webpack-redux
5 silly fetchNamedPackageData react-webpack-redux
6 silly mapToRegistry name react-webpack-redux
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'react-webpack-redux',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   escapedName: 'react-webpack-redux',
9 silly mapToRegistry   name: 'react-webpack-redux',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/react-webpack-redux
11 verbose request uri https://registry.npmjs.org/react-webpack-redux
12 verbose request no auth needed
13 info attempt registry request try #1 at 12:16:09
14 verbose request id 7f6fc39db9f3dc59
15 http request GET https://registry.npmjs.org/react-webpack-redux
16 http 404 https://registry.npmjs.org/react-webpack-redux
17 verbose headers { 'content-type': 'application/json',
17 verbose headers   'cache-control': 'max-age=0',
17 verbose headers   'content-length': '2',
17 verbose headers   'accept-ranges': 'bytes',
17 verbose headers   date: 'Sun, 06 Nov 2016 14:16:10 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   age: '0',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-gru7127-GRU',
17 verbose headers   'x-cache': 'MISS',
17 verbose headers   'x-cache-hits': '0',
17 verbose headers   'x-timer': 'S1478441769.578487,VS0,VE772',
17 verbose headers   vary: 'Accept-Encoding' }
18 silly get cb [ 404,
18 silly get   { 'content-type': 'application/json',
18 silly get     'cache-control': 'max-age=0',
18 silly get     'content-length': '2',
18 silly get     'accept-ranges': 'bytes',
18 silly get     date: 'Sun, 06 Nov 2016 14:16:10 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     age: '0',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-gru7127-GRU',
18 silly get     'x-cache': 'MISS',
18 silly get     'x-cache-hits': '0',
18 silly get     'x-timer': 'S1478441769.578487,VS0,VE772',
18 silly get     vary: 'Accept-Encoding' } ]
19 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/react-webpack-redux
19 silly fetchPackageMetaData     at makeError (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
19 silly fetchPackageMetaData     at Request._callback (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
19 silly fetchPackageMetaData     at Request.self.callback (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/request/request.js:187:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/request/request.js:1048:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/request/request.js:969:12)
19 silly fetchPackageMetaData  error for react-webpack-redux { Error: Registry returned 404 for GET on https://registry.npmjs.org/react-webpack-redux
19 silly fetchPackageMetaData     at makeError (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
19 silly fetchPackageMetaData     at Request._callback (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
19 silly fetchPackageMetaData     at Request.self.callback (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/request/request.js:187:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/request/request.js:1048:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/request/request.js:969:12) pkgid: 'react-webpack-redux', statusCode: 404, code: 'E404' }
20 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/react-webpack-redux
20 verbose stack     at makeError (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)
20 verbose stack     at CachingRegistryClient.<anonymous> (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:280:14)
20 verbose stack     at Request._callback (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:210:14)
20 verbose stack     at Request.self.callback (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/request/request.js:187:22)
20 verbose stack     at emitTwo (events.js:106:13)
20 verbose stack     at Request.emit (events.js:191:7)
20 verbose stack     at Request.<anonymous> (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/request/request.js:1048:10)
20 verbose stack     at emitOne (events.js:96:13)
20 verbose stack     at Request.emit (events.js:188:7)
20 verbose stack     at IncomingMessage.<anonymous> (/home/phellipe/.nvm/versions/node/v6.9.1/lib/node_modules/npm/node_modules/request/request.js:969:12)
21 verbose statusCode 404
22 verbose pkgid react-webpack-redux
23 verbose cwd /home/phellipe/Documentos/Projects/react-webpack-redux
24 error Linux 4.4.0-45-generic
25 error argv "/home/phellipe/.nvm/versions/node/v6.9.1/bin/node" "/home/phellipe/.nvm/versions/node/v6.9.1/bin/npm" "bugs" "react-webpack-redux"
26 error node v6.9.1
27 error npm  v3.10.9
28 error code E404
29 error 404 Registry returned 404 for GET on https://registry.npmjs.org/react-webpack-redux
30 error 404
31 error 404 'react-webpack-redux' is not in the npm registry.
32 error 404 You should bug the author to publish it (or use the name yourself!)
33 error 404 Note that you can also install from a
34 error 404 tarball, folder, http url, or git url.
35 verbose exit [ 1, true ]

##### Steps to Reproduce

1. npm install -g yo

2. npm install -g generator-react-webpack-redux

3. npm install -g phantomjs-prebuilt

4. yo react-webpack-redux

5. npm start or npm run serve:dev

I am available for any possible question, thanks.

**Comment by phellipeandrade** [comment] 2016-11-06 14:34
yeoman doctor

Yeoman Doctor

Running sanity checks on your system

✔ Global configuration file is valid
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✔ NODE_PATH matches the npm root

**Comment by eastbayjake** [comment] 2016-11-15 02:27
Looks like a duplicate of #46, try `npm install webpack@2.1.0-beta.6`

**Comment by stylesuxx** [comment] 2016-11-15 21:36
Again, @eastbayjake thank you - this should fix the problem. @phellipeandrade can you confirm?

**Comment by phellipeandrade** [comment] 2016-11-20 21:13
Thank you guys! it works.

**Closed** 2016-11-20 21:58 UTC
Labels: duplicate
