### ISSUE TITLE
warning  'state' is defined but never used  no-unused-vars

### ISSUE THREAD

**Issue by TheoMer** [stylesuxx/generator-react-webpack-redux#33] opened 2016-07-22 13:34 UTC
OS: Windows 10 Pro
NPM: 3.9.5
Yo: 1.8.4

I took the following steps before seeing the above mentioned error in my command window:

1. npm install -g generator-react-webpack
2. cd into project folder
3. yo react-webpack
4. npm start

Note: See attached image.

![webpack error](https://cloud.githubusercontent.com/assets/15969262/17058357/e5e3ee98-5017-11e6-8cf5-d0626601cce2.jpg)

**Comment by janek26** [comment] 2016-07-26 14:07
You should use your state then? I think it is not a "bug", its is just because you did not create components using your state yet. You should look deeper into Redux and understand the state object, before opening more issues.

**Comment by stylesuxx** [comment] 2016-07-26 14:24
As @janek26 mentioned, this is not a bug, just a warning. I have warnings enabled in the linter, so it warns you when you have variables that you are not using.

Since the project is new, the state is not yet used anywhere since no components are consuming it.

**Comment by TheoMer** [comment] 2016-07-26 15:04
@stylesuxx No worries. For some reason I had it in mind that there would be some redux boilerplate. @janek26

**Comment by TheoMer** [comment] 2016-07-26 15:06
@stylesuxx No worries. I had it it mind that there would be some redux boilerplate. @janek26

**Comment by stylesuxx** [comment] 2016-07-26 18:04
There is, but when you generate a new project, you basically have an empty container and nothing is consuming the state.

I am closing this down. Feel free to re open if you have any questions.

**Closed by stylesuxx** 2016-07-26 18:04 UTC
Labels: question
