### ISSUE TITLE
npm can't start, web pack version issue?

### ISSUE THREAD

**Issue by mkliu** [stylesuxx/generator-react-webpack-redux#53] opened 2016-11-13 06:56 UTC
throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'debug'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   The 'debug' property was removed in webpack 2.
   Loaders should be updated to allow passing this option via loader options in module.rules.
   Until loaders are updated one can use the LoaderOptionsPlugin to switch loaders into debug mode:
   plugins: {
     new webpack.LoaderOptionsPlugin({
       debug: true
     })
   }
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, loaders?, noParse?, rules?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   Options affecting the normal modules (`NormalModuleFactory`).
 - configuration.resolve.extensions[0] should not be empty.
    at webpack (/Users/wayliu/src/goodmom/private/my-new-project/node_modules/webpack/lib/webpack.js:16:9)
    at Object.<anonymous> (/Users/wayliu/src/goodmom/private/my-new-project/node_modules/webpack-dev-server/bin/webpack-dev-server.js:236:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)

**Comment by eastbayjake** [comment] 2016-11-15 02:27
Looks like a duplicate of #46, try `npm install webpack@2.1.0-beta.6` then `npm start` again

**Comment by stylesuxx** [comment] 2016-11-15 21:34
Thank you @eastbayjake this should do the trick, @mkliu can you confirm?

**Comment by stylesuxx** [comment] 2017-01-28 02:39
Closing this, webpack is stable now, this should no longer be an issue - at least in develop

**Closed by stylesuxx** 2017-01-28 02:39 UTC
Labels: duplicate
